FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
COPY cfg/supervisord.conf /etc/
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
CMD supervisord -c /etc/supervisord.conf && supervisorctl status all && tail -f /var/log/qualys_worker*
#CMD find / -name supervisord